"""add symptoms column to patient

Revision ID: 4e9d859ce8f1
Revises: 489d6ac46ba4
Create Date: 2025-06-23 14:08:21.136927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4e9d859ce8f1'
down_revision: Union[str, Sequence[str], None] = '489d6ac46ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'patient',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name',  sa.String(), nullable=False),
        sa.Column('date_of_birth', sa.Date(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('symptoms', sa.Text(), nullable=True),
    )
    op.create_index('ix_patient_email', 'patient', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prediction', type_='foreignkey')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
