"""add is_admin to user

Revision ID: 71bd511ae2b6
Revises: ba75d617bc77
Create Date: 2025-06-20 16:09:01.074966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bd511ae2b6'
down_revision: Union[str, Sequence[str], None] = 'ba75d617bc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'label')
    op.drop_column('prediction', 'timestamp')
    op.drop_column('prediction', 'user_id')
    op.drop_column('prediction', 'probability')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.add_column('prediction', sa.Column('probability', sa.FLOAT(), nullable=False))
    op.add_column('prediction', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('prediction', sa.Column('timestamp', sa.DATETIME(), nullable=False))
    op.add_column('prediction', sa.Column('label', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
