name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi sqlmodel uvicorn pytest flake8 mypy

      - name: Create tests folder & dummy test
        run: |
          mkdir -p tests
          echo "# tests package" > tests/__init__.py
          cat << 'EOF' > tests/test_dummy.py
          def test_dummy():
              assert True
          EOF

      - name: Lint with flake8 (report only, never fail)
        run: |
          flake8 app tests \
            --max-line-length=120 \
            --exit-zero

      - name: Type check with mypy
        run: |
          mypy app --ignore-missing-imports

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
